### ISSUE TITLE
2GB memory allocation for 2k headers

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/portable-mds#14]
It seems that there is a large memory footprint for the database when running around 2k headers.
Running on xpd ws6 it seems to be about a 2GB difference between instantiating the databroker and asking for the latest header. When requesting the latest header it seems that MDS tries to read all the `.sqlite` files in the directory, running on our 1GB computer this fills the memory (to a point) at which we get a cant open database error, which I think is due to the memory footprint.
I have moved all the instances of `fetchall` to be iterators so those don't seem to be the problem.
Thoughts?
@danielballan @tacaswell @arkilic

**Comment by arkilic** [comment]
Before we dig in: a computer with 1 GB memory in year 2017!? My watch has more :)

**Comment by tacaswell** [comment]
Indeed, this should probably be fixed by upgrading ws6.

**Comment by CJ-Wright** [comment]
Its not ws6, its a toy AWS instance

**Comment by CJ-Wright** [comment]
Here is the error
```python
Traceback (most recent call last):
  File "/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15470, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 3634, in run_compiled_code
    func(code, glb, loc)
  File "./exp_db_start.xsh", line 1, in <module>
    print("Initial PDFitc")
  File "/home/deployment/other_src/databroker/databroker/broker.py", line 344, in __getitem__
    start, stop in search(key, self)]
  File "/home/deployment/miniconda3/envs/db1/lib/python3.5/functools.py", line 745, in wrapper
  File "/home/deployment/other_src/databroker/databroker/broker.py", line 202, in _
    result = next(gen)
  File "/home/deployment/other_src/portable-mds/portable_mds/template/mds.py", line 378, in find_last
  File "/home/deployment/other_src/portable-mds/portable_mds/sqlite/mds.py", line 214, in _runstart_col
  File "/home/deployment/other_src/portable-mds/portable_mds/sqlite/mds.py", line 236, in _event_col
  File "/home/deployment/other_src/portable-mds/portable_mds/sqlite/mds.py", line 69, in __init__
  File "/home/deployment/other_src/portable-mds/portable_mds/sqlite/mds.py", line 81, in reconnect
sqlite3.OperationalError: unable to open database file
```

**Comment by CJ-Wright** [comment]
Note that this error no also occurs when we aren't occupying all of the memory

**Comment by danielballan** [comment]
More information is needed to follow up. Do these headers have large arrays in them (masks, for example)? What's the size of the sqlite file? Please open a new issue against databroker if this is still relevant and you can collect new information.
